apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-nginx-rules
  namespace: monitoring
spec:
  groups:
    - name: counter
      rules:
        #host
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_3XX
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"3.."}[1m])) by (host)
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_4XX
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"40[^3]{1}|4[^0]{1}."}[1m])) by (host)
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_5XX
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"5.."}[1m])) by (host)
        #host,path
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_path_3XX
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"3.."}[1m])) by (host, path)
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_path_4XX
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"40[^3]{1}|4[^0]{1}."}[1m])) by (host, path)
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_path_5XX
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"5.."}[1m])) by (host, path)
        #host,path,instance
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_3XX_path_instance
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"3.."}[1m])) by (host,path,instance)
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_5XX_path_instance
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"5.."}[1m])) by (host,path,instance)
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_4XX_path_instance
          expr: sum(increase(nginx_request_duration_seconds_count{status=~"40[^3]{1}|4[^0]{1}."}[1m])) by (host,path,instance)
        #host,path,instance,status
        - record: job:nginx_request_duration_seconds_count:counter_1min_by_host_status_path_instance
          expr: sum(increase(nginx_request_duration_seconds_count{}[1m])) by (host,status,path,instance)
  #    - record: job:nginx_request_duration_seconds_count:err_counter_403_by_path_instance
  #      expr: sum(nginx_request_duration_seconds_count{status="403"}) by (path, instance)
  #    - record: job:nginx_request_duration_seconds_count:err_counter_403_by_path_host_instance
  #      expr: sum by(path, host, instance) (nginx_request_duration_seconds_count{status="403"})
  #    - record: job:nginx_request_duration_seconds_count:counter_by_host
  #      expr: count(count(nginx_request_duration_seconds_count) by (host, instance)) by (host)